### ISSUE TITLE
请教作者一些问题

### ISSUE THREAD

**Issue by 192114** [zmtom18988tmd/chinese-acupuncture-point#1]
首先，非常感谢作者开源了这个模型，本人没有建模相关的知识。

导出模型为glb格式，遇到了模型透视，还有标记线位置不对的情况。

由于基础知识匮乏，并没有搜索到解决的办法，希望作者能够赐教。

https://github.com/zmtom18988tmd/chinese-acupuncture-point/assets/38213592/0342db43-0254-4cdd-82a8-883022818a01

感谢，并期待您的解答

blender 的版本是3.6
threejs 是最新版

**Comment by zj2050** [comment]
> 首先，非常感谢作者开源了这个模型，本人没有建模相关的知识。
> 
> 导出模型为glb格式，遇到了模型透视，还有标记线位置不对的情况。
> 
> 由于基础知识匮乏，并没有搜索到解决的办法，希望作者能够赐教。
> 
>  64ccdb309423fe913c2c173557a457d7.mp4 
> 感谢，并期待您的解答
> 
> blender 的版本是3.6 threejs 是最新版

@192114 你好，你的问题解决了吗？ 方便沟通一下，qq：1901324058
